# This file was generated by GoReleaser and patched to use the published
# release archive checksums from https://github.com/ehmo/gum/releases.
cask "gum" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "104f160748845525663ba8288094a3e0b6ca76e7362d59fbaa9d2f0f24314cca"
      url "https://github.com/ehmo/gum/releases/download/v#{version}/gum_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7da209f447fc850bcef769e2eee904b0fa443dd8e901ddcfcc3775f764885cbc"
      url "https://github.com/ehmo/gum/releases/download/v#{version}/gum_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c74d07033c1c4d6897ea55b539c80d7df2f5ca1f1fceebe1ab4ab5a270774695"
      url "https://github.com/ehmo/gum/releases/download/v#{version}/gum_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc1fbcc570a764cde99b42fd400c328e12f829b85e18324d598b20007a8b980b"
      url "https://github.com/ehmo/gum/releases/download/v#{version}/gum_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gum"
  desc "Google Universal MCP - single Go binary CLI and MCP stdio server with the Google capability catalog"
  homepage "https://github.com/ehmo/gum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gum"
end
