# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghealth < Formula
  desc "Unofficial Google-Health-CLI for the Google Health API"
  homepage "https://github.com/rudrankriyam/Google-Health-CLI"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.0.0/ghealth_1.0.0_darwin_amd64.tar.gz"
      sha256 "48e7d75213adb0203b7d94c570cbbdba4479f3bd8369713acbda08301b308e5d"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.0.0/ghealth_1.0.0_darwin_arm64.tar.gz"
      sha256 "86f61015f114940c344f72187f7380c265be725d0276ede32a3d4c84f01bf645"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.0.0/ghealth_1.0.0_linux_amd64.tar.gz"
      sha256 "3ff7efe71483cc13d59ffb6f1f272220bda8c7ef940d299caee5c5854d894c49"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.0.0/ghealth_1.0.0_linux_arm64.tar.gz"
      sha256 "442500bd8d540c3f7ec730c9073c2cdb1647f9c85390ff7cf3b633228816027d"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  test do
    system "#{bin}/ghealth", "version"
  end
end
