# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghealth < Formula
  desc "Unofficial Google-Health-CLI for the Google Health API"
  homepage "https://github.com/rudrankriyam/Google-Health-CLI"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.0.0/ghealth_1.0.0_darwin_amd64.tar.gz"
      sha256 "338d9d546e8fc16c589176a03e33df25ca956cda564d5683a4981c3b79cbc628"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.0.0/ghealth_1.0.0_darwin_arm64.tar.gz"
      sha256 "90cd431f2047bf25937d1c637ba40eeb23e31d49a4e6efc041a885e4f7da967a"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.0.0/ghealth_1.0.0_linux_amd64.tar.gz"
      sha256 "7952c32e58bc13f49969e7c5598864abaa5e7205ca332c94e1fa99491c8e1d3d"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.0.0/ghealth_1.0.0_linux_arm64.tar.gz"
      sha256 "f264299b6314957f788c34d591e52ccb40bfe04beff647066f50c27cf2a7a26c"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  test do
    system "#{bin}/ghealth", "version"
  end
end
